# Generated by Django 5.1.2 on 2024-12-21 12:54

import service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default=service.models.get_default_email, max_length=254)),
                ('name', models.CharField(max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
            options={
                'db_table': 'NewCartItems',
            },
        ),
        migrations.DeleteModel(
            name='CartItems',
        ),
    ]
